ELETTRA_LAMBORGHINI/urls.py
from django.conf import settings
from django.contrib import admin

from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include, re_path
from django.conf.urls.static import static

urlpatterns = [
    path('', include("agents.urls", namespace="agents")),
    path('products/', include("product.urls")),
    path('order/', include("order.urls")),
    
    #re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
   prefix_default_language=False,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "agents"
urlpatterns = [
    path("", views.index, name="index"),
    path("agent/<str:agent_name>/orders/", views.agent, name="agent"),
    path("agent/<str:agent_name>/customers/", views.customers, name="customers"),
    path("agent/<str:agent_name>/add-customer/", views.add_customer, name="add_customer"),
    path("redirectToProducts/<int:customer_id>", views.redirectToProducts, name="redirectToProducts"),
    path("agent/products/", views.products, name="products"),
    path("agent/products/<int:id>/<slug:slug>/", views.detailed_product, name="detailed_product"),
    path("products/orders/", views.orders, name="orders"),
    path("", views.doLogout, name="doLogout"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor')
    #path('addtocart/', views.addtocart, name='addtocart')        
]

order/urls.py
from django.urls import path

from . import views

app_name = "order"

urlpatterns = [
    path('', views.index, name='index'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('addtocart_w_v/<int:product_id>', views.addtocart_without_variant, name='addtocart_without_variant'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderPlace/', views.orderPlace, name='orderPlace'),
    path('order_completed/<str:ordercode>', views.order_completed, name='order_completed'),
    path('all-orders/', views.orders, name='orders'),
    path('order-details/<int:order_id>', views.order_detailed, name='order_detailed')
]

product/urls.py
from django.urls import path

from . import views
app_name = "product"
urlpatterns = [
    path('', views.index, name='index')
    
]

agents/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
#from phonenumber_field.modelfields import PhoneNumberField
User = get_user_model

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    phone = models.IntegerField()
    region = models.CharField(max_length=64)
    billing_address = models.CharField(max_length=400)
    delivery_address = models.CharField(max_length=400)
    vat_number = models.IntegerField()
    pub_date = models.DateTimeField('date published')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="agent", blank=True)

    def __str__(self):
        return f"{self.name} | {self.email} | {self.phone} | {self.region} | {self.billing_address} | {self.delivery_address} | {self.vat_number}"

agents/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models.query import QuerySet

from django.template.loader import render_to_string

from django.utils.timezone import localtime, now

from .models import Customer
from product.models import Category, Product, Images, Comment, Variants, Color
from order.models import ShopCart

#from django.contrib.auth.models import User
#settings.AUTH_USER_MODEL



# Create your views here.

def index(request):
    if request.method == "POST":
        username = request.POST["username"]
        userpass = request.POST["inputPass"]
        
        user = authenticate(username=username, password=userpass)

        if user:
            login(request, user)
            agent_name = request.user.username
            return HttpResponseRedirect(reverse("agents:agent", args=[agent_name]))
        else:
            return render(request, "agents/index.html", {
                "message" : "Email or password is incorrect!"
            })        
    else:
        logout(request)
        return render(request, "agents/index.html")

def agent(request, agent_name):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("agents:index"))
    else:
        user = request.user
        return render(request, "agents/agent.html", {
            "user": user
        })    

def customers(request, agent_name):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("agents:index"))
    else:
        user = request.user
        customers = Customer.objects.filter(created_by=user)
        #.all()

        if request.method == "POST":
            selected_customer = request.POST["customer"]
            request.session["selected_customer"] = [selected_customer]
            return HttpResponseRedirect(reverse("agents:products"))

        return render(request, "agents/customers.html", {
            "user": user,
            "agent_name": agent_name,
            "customers": customers
        }) 

def redirectToProducts(request, customer_id):
    request.session["selected_customer"] = [customer_id]
    return HttpResponseRedirect(reverse("agents:products"))

def products(request):
    if not request.user.is_authenticated:
        if "selected_customer" not in request.session:
            request.session["selected_customer"] = []
        
        return HttpResponseRedirect(reverse("agents:index"))
    else:
        list = request.session["selected_customer"]
        c = Customer.objects.get(pk=list[0])
        user = request.user
        if request.method == 'GET':
            query = request.GET.get('q', None)
            if query:
                latest_products = Product.objects.filter(title__icontains=query)
                return render(request, "agents/products.html", {
                    
                    "user": user,
                    "selected_c": c,
                    "latest_products": latest_products

                })
            else:
                latest_products = Product.objects.all()
                return render(request, "agents/products.html", {
                    "user": user,
                    "selected_c": c,
                    "latest_products": latest_products

                })    
                #template = loader.get_template()
        else:    
            #context = Context({ 'query': query, 'results':results })
            latest_products = Product.objects.all().order_by('-id')[:4]
            return render(request, "agents/products.html", {
            "user": user,
            "selected_c": c,
            "latest_products": latest_products

            })
        latest_products = Product.objects.all().order_by('-id')[:4]
        return render(request, "agents/products.html", {
            "user": user,
            "selected_c": c,
            "latest_products": latest_products

        })    

def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Product.objects.filter(title__icontains=query)
        else:
            return Product.objects.all()

def detailed_product(request, id, slug):
    query = request.GET.get('query')
    list = request.session["selected_customer"]
    c = Customer.objects.get(pk=list[0])
    user = request.user
    category = Category.objects.all()

    product = Product.objects.get(pk=id)

    images = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id=id,status='True')
    context = {'product': product,'category': category,
               'images': images, 'comments': comments, "selected_c": c,
               }
    if product.variant !="None": # Product have variants
        if request.method == 'POST': #if we select color
            variant_id = request.POST.get('variantid')
            variant = Variants.objects.get(id=variant_id) #selected product by click color radio
            colors = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY color_id',[id])
            #colors = Variants.objects.filter(product_id=id,size_id=variant.size_id )
            sizes = Variants.objects.filter(product_id=id,color_id=variant.color_id)
            query += variant.title+' Size:' +str(variant.size) +' Color:' +str(variant.color)
        else:
            variants = Variants.objects.filter(product_id=id)
            #colors = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY color_id',[id])
            colors = Variants.objects.filter(product_id=id).distinct('color_id')
            print(colors)

            colors.group_by = ['color_id'] 
            
            results = QuerySet(query=colors, model=Variants)
            #print(results)
            #raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY color_id',[id])
            #colors = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY color_id',[id])
            #colors = Variants.objects.filter(product_id=id,size_id=variants[0].size_id )
            #sizes = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY size_id',[id])
            sizes = Variants.objects.filter(product_id=id,color_id=variants[0].color_id )
            variant = Variants.objects.get(id=variants[0].id)
        context.update({'sizes': sizes, 'colors': colors,
                        'variant': variant,'query': query, "selected_c": c
                        })
    else:
        context.update({
            'product': product,
            'images': images,
            'selected_c': c
        })                    
    return render(request,'agents/detailed-product.html',context)

    '''
    product = Product.objects.get(pk=product_id)
    v = Variants.objects.filter(product=product_id)
    variants = Variants.objects.filter(product_id=product_id)

    colors = Variants.objects.filter(product_id=product_id,size_id=variants[0].size_id )
    sizes = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY size_id',[product_id])
    variant =Variants.objects.get(id=variants[0].id)
    return render(request, "agents/detailed-product.html", {
        "user": user,
        "selected_c": c,
        "product" : product,
        'sizes': sizes, 
        'colors': colors,
        'vt': v,
        'variant': variant
    })'''



def ajaxcolor(request):
    data = {}
    if request.POST.get('action') == 'post':
        color_id = request.POST.get('color')
        productid = request.POST.get('productid')
        sizes = Variants.objects.filter(product_id=productid, color_id=color_id)
        context = {
            'color_id': color_id,
            'productid': productid,
            'sizes': sizes,
        }
        data = {'rendered_table': render_to_string('agents/size_list.html', context=context)}
        return JsonResponse(data)
    return JsonResponse(data)    
    
def orders(request):
    list = request.session["selected_customer"]
    c = Customer.objects.get(pk=list[0])
    user = request.user
    return render(request, "agents/detailed-product.html", {
        "user": user,
        "selected_c": c
    })    



def analytics(request):
    return HttpResponse("analytics")

def settings(request):
    return HttpResponse("settings")

def doLogout(request):
    logout(request)
    return render(request, "agents/index.html", {
        "message": "Logged Out"
    })   

def add_customer(request, agent_name):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("agents:index"))
    else:
        if request.method == "POST":
            name = request.POST["name"]
            email = request.POST["email"]
            phone = request.POST["phone"]
            region = request.POST["region"]
            billing_address = request.POST["billing_address"]
            delivery_address = request.POST["delivery_address"]
            vat_number = request.POST["vat_number"]
            
            u = User.objects.get(username=agent_name)
            c = Customer(name=name, email=email, phone=phone, region=region, billing_address=billing_address, delivery_address=delivery_address, vat_number=vat_number, pub_date=localtime(now()), created_by=u)
            c.save()
            return HttpResponseRedirect(reverse("agents:customers", args=[agent_name]))

        user = request.user
        return render(request, "agents/add-customer.html", {
            "user": user,
            "agent_name": agent_name
        })
'''
def addtocart(request):
    data = {}
    if request.POST.get('action') == 'post':
        product_id = request.POST.get("product_id")
        variant_id = request.POST.get("size")

product/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render



# Create your views here.
def index(request):
   return  HttpResponse("My Product Page")

agents/templates/agents/agent.html
{% extends "agents/layout.html" %}

{% block title %}
  {% if user%}
    Ordini | {{user|capfirst}}
  {% endif %}
{% endblock %}



{% block body %}

{% include "agents/sidenav.html" %}
    
    <div class="parent-div-order-page">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-xs-10 col-sm-10 col-md-8 col-lg-6 offset-xs-1 offset-sm-1 offset-md-2 offset-lg-3">
                    <div>
                        <div class=" col-xs-12 col-sm-12 col-md-10 col-lg-10 offset-md-1 offset-lg-1">
                            <div class="btn-toolbar" role="toolbar">
                                <div style="width: 50%;" class="btn-group" role="group">
                                    <a href="{% url 'order:orders' %}" id="submit-button" type="button" class="btn btn-success btn-lg">Visualizza tutti gli ordini</a>
                                    &nbsp;
                                </div>
                                
                                <div style="width: 50%;" class="btn-group" role="group">
                                    &nbsp;
                                    <a href="{% url 'agents:customers' user.username %}" id="submit-button" type="button" class="btn btn-success btn-lg">Fai un nuovo ordine</a>
                            
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        

{% endblock %}

agents/templates/agents/customers.html
{% extends "agents/layout.html" %}
{% load static %}
{% block title %}
  {% if user%}
    Cliente | {{user.username|capfirst}}
  {% endif %}
{% endblock %}



{% block body %}

{% include "agents/sidenav.html" %}
    <div class="parent-div-products-page ">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-12 mt-1 mb-3">
                    <div style="float: right;" class="btn-group" role="group">
                        <small>Crea Nuovo Cliente? &nbsp;<a href="{% url 'agents:add_customer' user.username %}">Clicca qui</a></small>
                    </div>
                </div>
                {% if customers %}
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="customers_table" class="table table-striped">
                                <thead>
                                <tr>
                                    <th align="center">Sr #</th>  
                                    <th>Nome</th>
                                    <th>Email</th>
                                    <th>Numero di Telefono</th>
                                    <th>Regione</th>
                                    <th>Indirizzo di Fatturazione</th>
                                    <th>Indirizzo di Consegna</th>
                                    <th>P.Iva</th>
                                    <th>Azione</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for customer in customers %}
                                <tr class="col-form-label col-form-label-sm">
                                        <td align="center">{{ forloop.counter }}</td>
                                        <td>{{customer.name|capfirst}}</td>
                                        <td>{{customer.email}}</td>
                                        <td>{{customer.phone}}</td>
                                        <td>{{customer.region|capfirst}}</td>
                                        <td>{{customer.billing_address}}</td>
                                        <td>{{customer.delivery_address}}</td>
                                        <td>{{customer.vat_number}}</td>
                                        <td>
                                            <a href="{% url 'agents:redirectToProducts' customer.id %}" class="btn btn-success btn-sm">Continua <i class="fas fa-arrow-circle-right"></i></a>
                                        </td>
                                    
                                    
                                </tr>
                                {% endfor %} 
                                </tbody>
                            </table>
                        </div>   
                    </div>
                {% else %}
                    <div align="center" class="col-12 mt-5">
                        <img class="w-25" src="{% static 'agents/images/not_found.svg' %}"/>
                        <h5 class="col-form-label col-form-label-md pt-3">Nessun cliente esiste.</h5>
                      </div>
                {% endif %}
            </div>
        </div>
    </div>
        

{% endblock %}

agents/templates/agents/detailed-product.html
{% extends "agents/layout.html" %}

{% block title %}
  {% if user%}
  {{product.title}} | {{user|capfirst}}
  {% endif %}
{% endblock %}



{% block body %}
{% include "agents/sidenav.html" %}
<div>
    {% include "agents/product-page-header.html" %}
</div>
<main class="container pb-5">
 
    <div class="row">
        <div class="col-12">
            <div id="addedToCart">
                
            </div>
        </div>
        
        <!-- Left Column / Headphones Image -->
    <div align="center" class="col-xs-12 col-sm-12 col-md-6 col-lg-6 mb-2">
        <div class="row">
            <div class="col-12">
                <div class=" mb-2">
                    <a href="{% url 'agents:products' %}" style="width: 100%; text-align: left;" class="btn btn-success btn-md"><i class="fas fa-arrow-circle-left"></i> Torna alla Collezione</a>
                </div>
            </div>
            <div  class="col-12">
                <img style="width: inherit;" data-image="black" src="{{MEDIA_URL}}{{product.image.url}}" alt="">
            </div>
        </div>
    </div>
     
     
      <!-- Right Column -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="pb-2" style="display: inline-block; left: 0; right: 0;;">
          <div class="pb-1 pt-1 pl-1 pr-1 mb-2 product-page-retail-price">
              <small>Prezzo Sell-In: {{product.retail_price}}</small>
          </div>
          <div class="pb-1 pt-1 pl-1 pr-1 product-page-wholesale-price">
              <small>Prezzo Sell-Out: {{product.wholesale_price}}</small> 
          </div>
        </div>
        <!-- Product Description -->
        <div class="product-description">
          <span>{{product.category}}</span>
          
          <h3>{{product.title}}</h3>
          <p>{{product.description|safe}}</p>
        </div>
     
        <!-- Product Configuration -->
        <div class="product-configuration">
            {% if product.variant != 'None' %}
          <!-- Product Color -->
          <div class="product-color">
            <script>
                $(document).on('change', '#post-form',function(e){
                    e.preventDefault();
                    $.ajax({
                        type:'POST',
                        url:'{% url "agents:ajaxcolor" %}',
                        data:{
                            productid:$('#productid').val(),
                            color:$('#color').val(),
                            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                            action: 'post'
                        },
                        data_type : 'html',
                        success: function (data) {
                            console.log("success");
                            $('#appendHere').html(data.rendered_table);
                        },
                        error: function (data) {
                            alert.log("Got an error" + data);
                        }
                    });
                });
            </script>
            <div class="color-option">
                {% for rs in colors %}
                    <div class="color-circle" style="background: {{rs.color.code}}; border:1px solid grey;"></div>
                {% endfor %}
                <form method="POST" id="post-form">
                    {% csrf_token %}
                    <input type="hidden" name="productid" id="productid" value="{{ product.id }}">
                    <lable for="color" class="col-form-label-sm">Colori:</lable>
                    
                    <select name="color" id="color" class="form-control form-control-sm">
                        {% for rs in colors %}
                            <option {% if variant.color_id == rs.color_id %} selected {% endif %} value="{{ rs.color_id }}">{{ rs.color.name }}</option>
                        {% endfor %}
                    </select>
                </form>
                
            </div>
            <div>
                <script>
                    $(document).on('submit', '#add-to-cart',function(e){
                        e.preventDefault();
                        $.ajax({
                            type:'POST',
                            url:'{% url "order:addtocart" %}',
                            data:{
                                product_id:$('#product_id').val(),

                                variantid_1M:$('#variantid-1M').val(),
                                variantid_3M:$('#variantid-3M').val(),
                                variantid_6M:$('#variantid-6M').val(),
                                variantid_9M:$('#variantid-9M').val(),
                                variantid_12M:$('#variantid-12M').val(),
                                variantid_1Y:$('#variantid-1Y').val(),
                                variantid_2Y:$('#variantid-2Y').val(),
                                variantid_4Y:$('#variantid-4Y').val(),
                                variantid_6Y:$('#variantid-6Y').val(),
                                variantid_8Y:$('#variantid-8Y').val(),
                                variantid_10Y:$('#variantid-10Y').val(),
                                variantid_12Y:$('#variantid-12Y').val(),
                                variantid_14Y:$('#variantid-14Y').val(),


                                size:$('#size').val(),
                                
                                q_1M:$('#q-1M').val(),
                                q_3M:$('#q-3M').val(),
                                q_6M:$('#q-6M').val(),
                                q_9M:$('#q-9M').val(),
                                q_12M:$('#q-12M').val(),
                                q_1Y:$('#q-1Y').val(),
                                q_2Y:$('#q-2Y').val(),
                                q_4Y:$('#q-4Y').val(),
                                q_6Y:$('#q-6Y').val(),
                                q_8Y:$('#q-8Y').val(),
                                q_10Y:$('#q-10Y').val(),
                                q_12Y:$('#q-12Y').val(),
                                q_12Y:$('#q-14Y').val(),

                                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                                action: 'post'
                            },
                            data_type : 'html',
                            success: function (data) {
                                console.log("success");
                                //window.location = '{% url "order:addtocart" %}';
                                $('#addedToCart').html(data.rendered_table);
                            },
                            error: function (data) {
                                console.log("Got an error: " + data);
                            }
                        });
                    });
                </script>
                <form method="POST"  id="add-to-cart">
                    {% csrf_token %}
                    <div id="appendHere">
                        <div>
                            <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                            <lable for="size" class="col-form-label-sm">Taglie:</lable>
                            <div class="row">
                                {% for rs in sizes %}
                                <div class="col-sm-12 col-md-4 col-lg-2">
                                    <input type="hidden" type="number" id="variantid-{{ rs.size }}" name="variantid-{{ rs.size }}" value="{{ rs.id }}"/>
                                    <lable for="q-{{rs.size}}" class="col-form-label-sm"><span class="dot" style="width: 10px; height: 10px; background-color: {{rs.color.code}}; border:1px solid grey;"></span>{{ rs.size }}</lable>
                                    <input class="form-control form-control-sm add" style="width: inherit;" type="number" id="q-{{rs.size}}" name="q-{{rs.size}}" min="1" value=""/>
                                </div>
                                
                                {% endfor %}
                                
                            </div>
                            
                            <!--
                            <select name="size" id="size" class="form-control form-control-sm">
                                    {% for rs in sizes %}
                                        <option {% if variant.id == rs.id %} selected {% endif %} name="variantid" value="{{ rs.id }}">{{ rs.size }}</option>
                                    {% endfor %}
                            </select>
                            -->
                        </div>
                        <div style="width: 20%;" class="mt-3">
                            <lable for="quantity" class="col-form-label-lg">Quantità:</lable>
                            <input style="text-align: center;" id="quantity" type="name" name="quantity" required="" min="1" class="form-control form-control-lg" readonly required>
                        </div>
                        <script>
                            function sumOfIncome() {
                            var sum = 0;
                            $('.add').each(function() {
                                sum += parseInt(this.value) || 0;
                                console.log(sum)
                            });
                            $('#quantity').val(sum);
                            }
                            $('.add').blur(function() {
                            sumOfIncome();
                            })
                        </script>
                            <!--{% for rs in sizes %}
    
                                <p>{{rs.size}}</p>
                                {% if rs.size == '1M' %}
                                    <input type="number" placeholder="abc" name="{{rs.size}}" />
                                {% elif rs.size != '2M' %}
                                    <input type="number" placeholder="abc" name="{{rs.size}}" />
                                {% elif rs.size != '3M' %}
                                    <input type="number" placeholder="abc" name="{{rs.size}}" />
                                {% elif '1M' == '1M' %}
                                    <p>Hey</p>
                                {% else %}    
                                {% endif %}
                             {% endfor %}
                            -->      
                    </div>
                    <div class="mt-3">
                        <input style="width: 100%;" type="submit" value="Aggiungi al Carrello" class="btn btn-warning btn-lg"/>
                    </div>
                </form>
                
            </div> 
          </div>

            {% else %}
                
            <form method="post"  action="{% url 'order:addtocart_without_variant' product.id%}">
                {% csrf_token %}
                <div >
                    <div>
                        <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                    </div>
                    <div style="width: 20%;" class="mt-3">
                        <lable for="quantity" class="col-form-label-lg">Quantità:</lable>
                        <input style="text-align: center;" id="quantity" type="number" name="quantity" required="" min="1" class="form-control form-control-md" required>
                    </div>
                    
                </div>
                <div class="mt-3">
                    <input style="width: 100%;" type="submit" value="Aggiungi al Carrello" class="btn btn-warning btn-lg"/>
                </div>
            </form>
            
            {% endif %}
          
     
         
        </div>
     
        
      </div>
    
      <div class="col-12 mt-3">
        <h2 class="col-form-label col-form-label-lg">Dettagli Prodotto: </h2>
        <!-- Product Details -->
        <div class="product-description">
            <p>{{product.detail|safe}}</p>
          </div>
      </div>
  </main>

{% endblock %}